apiVersion: v1
kind: Service
metadata:
  name: macro-analyzer-service
spec:
  type: NodePort
  selector:
    app: macro-analyzer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
