INSERT INTO series_configuration (global_id, name, display_name, country, period, scrape_url)
VALUES (uuid_generate_v4(), 'PolicyRateSweden', 'PolicyRateSweden', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SECBREPOEFF/1994-06-01'),
       (uuid_generate_v4(), 'UsdSekExchangeRate', 'UsdSekExchangeRate', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SEKUSDPMI/1993-01-04'),
       (uuid_generate_v4(), 'GovernmentBondSweden2Year', 'GovernmentBondSweden2Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SEGVB2YC/1987-01-07'),
       (uuid_generate_v4(), 'GovernmentBondSweden5Year', 'GovernmentBondSweden5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SEGVB5YC/1985-01-02'),
       (uuid_generate_v4(), 'GovernmentBondSweden7Year', 'GovernmentBondSweden7Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SEGVB7YC/1987-01-02'),
       (uuid_generate_v4(), 'GovernmentBondSweden10Year', 'GovernmentBondSweden10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SEGVB10YC/1987-01-02'),
       (uuid_generate_v4(), 'GovernmentBillSweden1Month', 'GovernmentBillSweden1Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SETB1MBENCHC/1983-01-03'),
       (uuid_generate_v4(), 'GovernmentBillSweden3Month', 'GovernmentBillSweden3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SETB3MBENCH/1983-01-03'),
       (uuid_generate_v4(), 'GovernmentBillSweden6Month', 'GovernmentBillSweden6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SETB6MBENCH/1984-01-02'),
       (uuid_generate_v4(), 'GovernmentBillSweden12Month', 'GovernmentBillSweden12Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/SETB12MBENCH/1983-01-03'),
       (uuid_generate_v4(), 'EuroMarketRateDenmark3Month', 'EuroMarketRateDenmark3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MDKK/1981-11-12'),
       (uuid_generate_v4(), 'EuroMarketRateEur3Month', 'EuroMarketRateEur3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MEUR/1999-01-04'),
       (uuid_generate_v4(), 'EuroMarketRateGB3Month', 'EuroMarketRateGB3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations//EUDP3MGBP/1979-12-19'),
       (uuid_generate_v4(), 'EuroMarketRateJapan3Month', 'EuroMarketRateJapan3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MJPY/1979-11-29'),
       (uuid_generate_v4(), 'EuroMarketRateNorway3Month', 'EuroMarketRateNorway3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MNOK/1981-11-12'),
       (uuid_generate_v4(), 'EuroMarketRateUsa3Month', 'EuroMarketRateUsa3Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MUSD/1979-11-28'),
       (uuid_generate_v4(), 'EuroMarketRateDenmark6Month', 'EuroMarketRateDenmark6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP6MDKK/1981-11-12'),
       (uuid_generate_v4(), 'EuroMarketRateEur6Month', 'EuroMarketRateEur6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP6MEUR/1999-01-04'),
       (uuid_generate_v4(), 'EuroMarketRateGB6Month', 'EuroMarketRateGB6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP6MGBP/1979-11-28'),
       (uuid_generate_v4(), 'EuroMarketRateJapan6Month', 'EuroMarketRateJapan6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP3MJPY/1979-11-29'),
       (uuid_generate_v4(), 'EuroMarketRateNorway6Month', 'EuroMarketRateNorway6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP6MNOK/1981-11-12'),
       (uuid_generate_v4(), 'EuroMarketRateUsa6Month', 'EuroMarketRateUsa6Month', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EUDP6MUSD/1979-11-28'),
       (uuid_generate_v4(), 'IntGovBondsEur5Year',
        'IntGovBondsEur5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EMGVB5Y/1999-01-04'),
       (uuid_generate_v4(), 'IntGovBondsFrance5Year',
        'IntGovBondsFrance5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/FRGVB5Y/1988-02-08'),
       (uuid_generate_v4(), 'IntGovBondsGB5Year',
        'IntGovBondsGB5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/GBGVB5Y/1987-01-02'),
       (uuid_generate_v4(), 'IntGovBondsGermany5Year',
        'IntGovBondsGermany5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/DEGVB5Y/1987-02-09'),
       (uuid_generate_v4(), 'IntGovBondsJapan5Year',
        'IntGovBondsJapan5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/JPGVB5Y/1987-03-23'),
       (uuid_generate_v4(), 'IntGovBondsNetherlands5Year',
        'IntGovBondsNetherlands5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/NLGVB5Y/1987-02-09'),
       (uuid_generate_v4(), 'IntGovBondsUsa5Year',
        'IntGovBondsUsa5Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/USGVB5Y/1987-02-02'),
       (uuid_generate_v4(), 'IntGovBondsDenmark10Year',
        'IntGovBondsDenmark10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/DKGVB10Y/1982-01-04'),
       (uuid_generate_v4(), 'IntGovBondsEur10Year',
        'IntGovBondsEur10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/EMGVB10Y/1999-01-04'),
       (uuid_generate_v4(), 'IntGovBondsFinland10Year',
        'IntGovBondsFinland10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/FIGVB10Y/1990-04-02'),
       (uuid_generate_v4(), 'IntGovBondsFrance10Year',
        'IntGovBondsFrance10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/FRGVB10Y/1988-02-08'),
       (uuid_generate_v4(), 'IntGovBondsGB10Year',
        'IntGovBondsGB10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/GBGVB10Y/1987-01-02'),
       (uuid_generate_v4(), 'IntGovBondsGermany10Year',
        'IntGovBondsGermany10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/DEGVB10Y/1987-02-09'),
       (uuid_generate_v4(), 'IntGovBondsJapan10Year',
        'IntGovBondsJapan10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/JPGVB10Y/1987-01-05'),
       (uuid_generate_v4(), 'IntGovBondsNetherlands10Year',
        'IntGovBondsNetherlands10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/NLGVB10Y/1987-02-09'),
       (uuid_generate_v4(), 'IntGovBondsNorway10Year',
        'IntGovBondsNorway10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/NOGVB10Y/1990-05-31'),
       (uuid_generate_v4(), 'IntGovBondsUsa10Year',
        'IntGovBondsUsa10Year', '', '',
        'https://api.riksbank.se/swea/v1/Observations/USGVB10Y/1991-01-02');
