INSERT INTO series_configuration (global_id, name, display_name, country, period)
VALUES (uuid_generate_v4(), 'PolicyRateSweden', 'PolicyRateSweden', '', ''),
       (uuid_generate_v4(), 'UsdSekExchangeRate', 'UsdSekExchangeRate', '', ''),
       (uuid_generate_v4(), 'GovernmentBondSweden2Year', 'GovernmentBondSweden2Year', '', ''),
       (uuid_generate_v4(), 'GovernmentBondSweden5Year', 'GovernmentBondSweden5Year', '', ''),
       (uuid_generate_v4(), 'GovernmentBondSweden7Year', 'GovernmentBondSweden7Year', '', ''),
       (uuid_generate_v4(), 'GovernmentBondSweden10Year', 'GovernmentBondSweden10Year', '', ''),
       (uuid_generate_v4(), 'GovernmentBillSweden1Month', 'GovernmentBillSweden1Month', '', ''),
       (uuid_generate_v4(), 'GovernmentBillSweden3Month', 'GovernmentBillSweden3Month', '', ''),
       (uuid_generate_v4(), 'GovernmentBillSweden6Month', 'GovernmentBillSweden6Month', '', ''),
       (uuid_generate_v4(), 'GovernmentBillSweden12Month', 'GovernmentBillSweden12Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateDenmark3Month', 'EuroMarketRateDenmark3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateEur3Month', 'EuroMarketRateEur3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateGB3Month', 'EuroMarketRateGB3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateJapan3Month', 'EuroMarketRateJapan3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateNorway3Month', 'EuroMarketRateNorway3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateUsa3Month', 'EuroMarketRateUsa3Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateDenmark6Month', 'EuroMarketRateDenmark6Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateEur6Month', 'EuroMarketRateEur6Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateGB6Month', 'EuroMarketRateGB6Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateJapan6Month', 'EuroMarketRateJapan6Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateNorway6Month', 'EuroMarketRateNorway6Month', '', ''),
       (uuid_generate_v4(), 'EuroMarketRateUsa6Month', 'EuroMarketRateUsa6Month', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsEur5Year',
        'InternationalGovernmentBondsEur5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsFrance5Year',
        'InternationalGovernmentBondsFrance5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsGB5Year',
        'InternationalGovernmentBondsGB5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsGermany5Year',
        'InternationalGovernmentBondsGermany5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsJapan5Year',
        'InternationalGovernmentBondsJapan5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsNetherlands5Year',
        'InternationalGovernmentBondsNetherlands5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsUsa5Year',
        'InternationalGovernmentBondsUsa5Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsDenmark10Year',
        'InternationalGovernmentBondsDenmark10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsEur10Year',
        'InternationalGovernmentBondsEur10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsFinland10Year',
        'InternationalGovernmentBondsFinland10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsFrance10Year',
        'InternationalGovernmentBondsFrance10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsGB10Year',
        'InternationalGovernmentBondsGB10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsGermany10Year',
        'InternationalGovernmentBondsGermany10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsJapan10Year',
        'InternationalGovernmentBondsJapan10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsNetherlands10Year',
        'InternationalGovernmentBondsNetherlands10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsNorway10Year',
        'InternationalGovernmentBondsNorway10Year', '', ''),
       (uuid_generate_v4(), 'InternationalGovernmentBondsUsa10Year',
        'InternationalGovernmentBondsUsa10Year', '', '');