export const rootUrl: string = 'http://localhost:8080';

export enum SAMPLE_SIZE {
  Full,
  Day,
  Month,
  Year,
}

export const allSamples = [
  SAMPLE_SIZE[SAMPLE_SIZE.Full],
  SAMPLE_SIZE[SAMPLE_SIZE.Day],
  SAMPLE_SIZE[SAMPLE_SIZE.Month],
  SAMPLE_SIZE[SAMPLE_SIZE.Year],
];

export const NO_FILTER = 'no_filter';

export const sampleToFilter = {
  [SAMPLE_SIZE.Full]: NO_FILTER,
  [SAMPLE_SIZE.Day]: NO_FILTER,
  [SAMPLE_SIZE.Month]: new RegExp(/^(\d{4}-\d{1,2})/),
  [SAMPLE_SIZE.Year]: new RegExp(/^(\d{4})/),
};

export enum DATASET_NAMES {
  SwedenPolicyRate,
  UsdSekExchangeRate,
  GovernmentBondSweden2Year,
  GovernmentBondSweden5Year,
  GovernmentBondSweden7Year,
  GovernmentBondSweden10Year,
  GovernmentBillSweden1Month,
  GovernmentBillSweden3Month,
  GovernmentBillSweden6Month,
  GovernmentBillSweden12Month,
  EuroMarketRateDenmark3Month,
  EuroMarketRateEur3Month,
  EuroMarketRateGB3Month,
  EuroMarketRateJapan3Month,
  EuroMarketRateNorway3Month,
  EuroMarketRateUsa3Month,
  EuroMarketRateDenmark6Month,
  EuroMarketRateEur6Month,
  EuroMarketRateGB6Month,
  EuroMarketRateJapan6Month,
  EuroMarketRateNorway6Month,
  EuroMarketRateUsa6Month,
  InternationalGovernmentBondsEur5Year,
  InternationalGovernmentBondsFrance5Year,
  InternationalGovernmentBondsGB5Year,
  InternationalGovernmentBondsGermany5Year,
  InternationalGovernmentBondsJapan5Year,
  InternationalGovernmentBondsNetherlands5Year,
  InternationalGovernmentBondsUsa5Year,
  InternationalGovernmentBondsDenmark10Year,
  InternationalGovernmentBondsEur10Year,
  InternationalGovernmentBondsFinland10Year,
  InternationalGovernmentBondsFrance10Year,
  InternationalGovernmentBondsGB10Year,
  InternationalGovernmentBondsGermany10Year,
  InternationalGovernmentBondsJapan10Year,
  InternationalGovernmentBondsNetherlands10Year,
  InternationalGovernmentBondsNorway10Year,
  InternationalGovernmentBondsUsa10Year,
}

export const allDatasetNames = [
  DATASET_NAMES[DATASET_NAMES.SwedenPolicyRate],
  DATASET_NAMES[DATASET_NAMES.UsdSekExchangeRate],
  DATASET_NAMES[DATASET_NAMES.GovernmentBondSweden2Year],
  DATASET_NAMES[DATASET_NAMES.GovernmentBondSweden5Year],
  DATASET_NAMES[DATASET_NAMES.GovernmentBondSweden7Year],
  DATASET_NAMES[DATASET_NAMES.GovernmentBondSweden10Year],
  DATASET_NAMES[DATASET_NAMES.GovernmentBillSweden1Month],
  DATASET_NAMES[DATASET_NAMES.GovernmentBillSweden3Month],
  DATASET_NAMES[DATASET_NAMES.GovernmentBillSweden6Month],
  DATASET_NAMES[DATASET_NAMES.GovernmentBillSweden12Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateDenmark3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateEur3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateGB3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateJapan3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateNorway3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateUsa3Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateDenmark6Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateEur6Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateGB6Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateJapan6Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateNorway6Month],
  DATASET_NAMES[DATASET_NAMES.EuroMarketRateUsa6Month],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsEur5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsFrance5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsGB5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsGermany5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsJapan5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsNetherlands5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsUsa5Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsDenmark10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsEur10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsFinland10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsFrance10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsGB10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsGermany10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsJapan10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsNetherlands10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsNorway10Year],
  DATASET_NAMES[DATASET_NAMES.InternationalGovernmentBondsUsa10Year],
];
