apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: macro-analyzer
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/postgres"
