'use client';

import './globals.css';
import 'tw-elements/dist/css/tw-elements.min.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import React from 'react';
import DrawerWrapper from '@/components/drawer/DrawerWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ClientLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <AppRouterCacheProvider>
      <DrawerWrapper>{children}</DrawerWrapper>
    </AppRouterCacheProvider>
  );
};

export default ClientLayout;
