'use client';

import './globals.css';
import { Inter } from 'next/font/google';
import 'tw-elements/dist/css/tw-elements.min.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import React from 'react';
import DrawerWrapper from '@/components/DrawerWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ClientLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <DrawerWrapper>{children}</DrawerWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default ClientLayout;
