import './globals.css';
import { Inter } from 'next/font/google';
import 'tw-elements/dist/css/tw-elements.min.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import DrawerWrapper from '@/components/drawer/DrawerWrapper';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// @ts-ignore
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <DrawerWrapper>{children}</DrawerWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
